language: python

# what pythons to test
python:
#  - "2.6"
  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "nightly"
  - "pypy"

# dont test feature branches
branches:
  only:
    - master
    - development

# install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libfuse-dev pkg-config fuse user-mode-linux
  - sudo mknod /dev/fuse c 10 229
  - sudo chmod 666 /dev/fuse
  - PYTHONPATH=$PYTHONPATH:./src # here is jottalib
install:
  - pip install -r tests/requirements.txt

# run tests
script:
  - py.test tests/
  - ./tests/fusetest.sh
