sudo: true
# we dont want to use the container based setup because fuse isnt available there, so we set "sudo: true"

language: python

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      python: 2.7
    - os: linux
      dist: trusty
      sudo: required
      python: 3.5
    - os: linux
      dist: trusty
      sudo: required
      python: pypy
    - os: osx
      osx_image: xcode7.2
      language: generic

# dont test feature branches
branches:
  only:
    - master

# ping these services with our results
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d39320d101700354362
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

# install dependencies
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update || brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python; fi
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq libfuse-dev pkg-config fuse user-mode-linux; sudo mknod /dev/fuse c 10 229; sudo chmod 666 /dev/fuse; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install osxfuse; sudo /bin/cp -RfX /usr/local/opt/osxfuse/Library/Filesystems/osxfusefs.fs /Library/Filesystems; sudo chmod +s /Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs; sudo mknod /dev/fuse c 10 229; sudo chmod 666 /dev/fuse; fi
install:
  - pip install -r tests/requirements.txt

# run tests
script:
  - PYTHONPATH=$PYTHONPATH:./src py.test tests/
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./tests/fusetest.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./tests/clitest.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo ./tests/fusetest.sh; fi 
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./tests/clitest.sh; fi
