# https://ci.appveyor.com/project/havardgulldahl/jottalib
build: false

environment:
  matrix:
    - PYTHON: "C:/Python27"
      LXML: "tests/contrib/lxml-3.6.4-cp27-cp27m-win32.whl"
      REQUIREMENTS: "test/requirements.txt"
    - PYTHON: "C:/Python34"
      LXML: "tests/contrib/lxml-3.6.4-cp35-cp35m-win32.whl"
      REQUIREMENTS: "test/requirements.txt"

init:
  - "ECHO %PYTHON%"
  - "ECHO %LXML%"
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/ez_setup.py" -OutFile "c:/ez_setup.py"
  - ps: Invoke-WebRequest "https://bootstrap.pypa.io/get-pip.py" -OutFile "c:/get-pip.py"
  - ps: "git config --global core.autocrlf false" # always use unix lineendings

install:
  - "%PYTHON%/python.exe c:/ez_setup.py > NUL"
  - "%PYTHON%/python.exe c:/get-pip.py"
  - "%PYTHON%/Scripts/pip.exe install %LXML%"
  - "%PYTHON%/Scripts/pip.exe -q install -r %REQUIREMENTS%"

test_script:
  - "%PYTHON%/Scripts/pip.exe --version"
  - "%PYTHON%/Scripts/http.exe --debug"
  - "%PYTHON%/python.exe setup.py test"